# File di configurazione per la generazione batch dei documenti
# Ogni voce specifica i file sorgente, il template e il file di destinazione (opzionale)

documenti:
  - data_filepath: "../data/programmazione_3_sia.yaml"
    template_filepath: "../templates/template_md_triennio.md"
    output_filename: "../output/Programmazione_3_SIA.md"
  - data_filepath: "../data/programmazione_3_sia.yaml"
    template_filepath: "../templates/TEMPLATE_Triennio_valutazione.docx"
    output_filename: "../output/Programmazione_3_SIA.docx"
    
