# File di configurazione per la generazione batch dei documenti
# Ogni voce specifica i file sorgente, il template e il file di destinazione (opzionale)

documenti:
  - data_filepath: "../data/programmazione_3_sia.yaml"
    template_filepath: "../templates/TEMPLATE_Triennio_valutazione.docx"
    output_filename: "../output/Programmazione_3_SIA.docx"

  - data_filepath: "../data/programmazione_3_sia.yaml"
    template_filepath: "../templates/template_md_triennio.md"
    output_filename: "../output/Programmazione_3_SIA.md"

  - data_filepath: "../data/programmazione_4_scientifico_sa.yaml"
    template_filepath: "../templates/TEMPLATE_MOD_INS_01_B REV.02 Programm. Dipart. Triennio.docx"
    output_filename: "../output/Programmazione_4_Scientifico_SA.docx"

  - data_filepath: "../data/programmazione_5_scientifico_sa.yaml"
    template_filepath: "../templates/TEMPLATE_MOD_INS_01_B REV.02 Programm. Dipart. Triennio.docx"
    output_filename: "../output/Programmazione_5_Scientifico_SA.docx"

  - data_filepath: "../data/programmazione_3_afm.yaml"
    template_filepath: "../templates/TEMPLATE_MOD_INS_01_B REV.02 Programm. Dipart. Triennio.docx"
    output_filename: "../output/Programmazione_3_AFM.docx"

  - data_filepath: "../data/programmazione_4_afm.yaml"
    template_filepath: "../templates/TEMPLATE_MOD_INS_01_B REV.02 Programm. Dipart. Triennio.docx"
    output_filename: "../output/Programmazione_4_AFM.docx"

  - data_filepath: "../data/programmazione_1_scientifico_sa.yaml"
    template_filepath: "../templates/MOD_INS_01_A REV.02 Programm. Dipart. Biennio.docx"
    output_filename: "../output/Programmazione_1_Scientifico_SA.docx"

  - data_filepath: "../data/programmazione_4_scientifico_cambridge.yaml"
    template_filepath: "../templates/TEMPLATE_MOD_INS_01_B REV.02 Programm. Dipart. Triennio.docx"
    output_filename: "../output/Programmazione_4_Scientifico_Cambridge.docx"

  - data_filepath: "../data/programmazione_1_afm.yaml"
    template_filepath: "../templates/MOD_INS_01_A REV.02 Programm. Dipart. Biennio.docx"
    output_filename: "../output/Programmazione_1_AFM.docx"

  - data_filepath: "../data/programmazione_2_afm.yaml"
    template_filepath: "../templates/MOD_INS_01_A REV.02 Programm. Dipart. Biennio.docx"
    output_filename: "../output/Programmazione_2_AFM.docx"
